volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  lsdata:
    driver: local

services:
  db:
    image: postgres
    command: -c max_connections=1000
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cnaught_event_travel
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: carbon0
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql

  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "db:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - db